---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=1000${PGID}
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ${SERVERS}/data:/data
      # - /path/to/tvseries:/tv #optional
      # - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
